# Project information
site_name: d.ASH SDK
site_url: https://dconstruct-tech.github.io/dash-sdk/
site_author: dConstruct Technologies Team

# Repository
repo_name: dconstruct-tech/dash-sdk
repo_url: https://github.com/dconstruct-tech/dash-sdk/
edit_uri: ""

theme:
  name: material
  # name: null
  # custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Barlow
    code: Roboto Mono
  logo: 'img/logo-white.png'
  favicon: 'img/logo.png'

  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - navigation.expand
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  font:
    text: Barlow
    code: Roboto Mono

# Plugins  
plugins:
  - search

# Customization
extra:
  homepage: https://www.dconstruct.co/

# Extensions
markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.highlight:
        linenums_style: pymdownx-inline
    - pymdownx.extra
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        clickable_checkbox: true

extra_css:
    - 'stylesheets/extra.css'


# Page tree
nav:
  - Home: 
    - Introduction: index.md
    - Our Products: home/products.md
    - Workflow : home/workflow.md
  - Setup:
    - 1.0 Installing Desktop Dependencies: setup/desktop-dep.md
    - 2.0 Payload Registration: setup/payload-reg.md
    - 3.0 Setting up d.ASH VPN: setup/vpn.md
    - 4.0 Setting up d.ASH: setup/dash.md
  - Getting Started:
    - 1.0 Configuring Spot: getting-started/config-spot.md
    - 2.0 Configuring Sensors: getting-started/config-connect.md
    - 3.0 Map Loading: getting-started/map-loading.md
    - 4.0 d.ASH with ROS: getting-started/dash-eng.md 
  - dC Pilot Guide: 
    - 1.0 d.ASH Pilot Client: dc-pilot/pilot-guide.md
    - 2.0 d.ASH Pilot SDK: dc-pilot/pilot-sdk.md
  - Autonomy Guide: 
    - 1.0 d.ASH Nav Desktop: dash-auto/autonomy-client-v2.md 
    - 1.1 d.ASH Nav Mobile: dash-nav/dash-nav.md
    - 1.2 d.ASH Nav Scripting API Reference: dash-auto/autonomy-client-v2-api-reference.md 
  - d.ASH Pack Guide: 
    - 1.0 d.ASH Pack: dash-pack/dash-pack.md 
    - 1.1 d.ASH Go: dash-pack/dash-go.md 
    - 2.0 d.ASH Xplorer: dash-pack/dash-xplorer.md 
  - SDK Configuration:
    - 1.0 d.ASH Service Configuration: sdk-config/rest-config.md
    - 2.0 Register Payload Configuration: sdk-config/register-bot.md
    - 3.0 Robot Configuration: sdk-config/robot-config.md
    - 4.0 Auto Configuration: sdk-config/auto-config.md
